In [ ]:
import numpy as np
A = np.array([[25,0,1],[20,1,2],[40,1,6]])
b = np.array([[110],[110],[210]])

# To invert a matrix, use:
A_inv=np.linalg.inv(A)


# To multiply matrices in Python 3, use:
A_inv@b

array([[ 4.25],
       [17.5 ],
       [ 3.75]])

In [ ]:
import numpy as np
A = np.array([[25,15,10,0,1],[20,12,8,1,2],[40,30,10,1,6], [30,15,15,0,3], [35,20,15,2,4]])
b = np.array([[104],[97],[193],[132],[174]])

# To see rank, use: 
# np.linalg.matrix_rank(A)
print(np.linalg.matrix_rank(A))

# Note: you can use np.hstack() to concatinate vectors, for example np.hstack((A,b))
print(np.linalg.matrix_rank(np.hstack((A, b))))

# Note: you can select all the columns, except the first of a matrix A as:  A[:,1:]
A_re=A[:,1:]

x=np.linalg.inv(np.transpose(A_re)@A_re)@np.transpose(A_re)@b

((A_re@x)-b)**2

Q=np.array([[1,-0.5,1],[0,1.5,0],[0,1.5,0],[1,-0.5,1]])
print(np.linalg.matrix_rank(Q))
print(np.transpose(Q)@Q)

W=np.array([[1,1],[1,-2],[1,1]])
new=Q@W
print(new)
b=np.array([[2],[1],[1],[2]])
x=np.linalg.inv(np.transpose(new)@new)@np.transpose(new)@b
print(x)

4
4
2
[[ 2. -1.  2.]
 [-1.  5. -1.]
 [ 2. -1.  2.]]
[[ 1.5  3. ]
 [ 1.5 -3. ]
 [ 1.5 -3. ]
 [ 1.5  3. ]]
[[1.        ]
 [0.16666667]]
