In [ ]:
import numpy as np
from scipy.io import loadmat
from scipy.sparse.construct import vstack
import math
from google.colab import drive 
#drive.mount('/content/drive')

def gram_schmidt(B):
    """Orthogonalize a set of vectors stored as the columns of matrix B."""
    # Get the number of vectors.
    m, n = B.shape
    # Create new matrix to hold the orthonormal basis
    U = np.zeros([m,n]) 
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto
        # each of the previous vectors.
        v = B[:,j].copy()
        for k in range(j):
            v -= np.dot(U[:, k], B[:, j]) * U[:, k]
        if np.linalg.norm(v)>1e-10:
            U[:, j] = v / np.linalg.norm(v)
    return U

if __name__ == '__main__':
    '''
    B1 = np.array([[1.0, 1.0, 0.0], [2.0, 2.0, 0.0], [2.0, 2.0, 1.0]])
    A1 = gram_schmidt(B1)
    print(A1)
    A2 = gram_schmidt(np.random.rand(4,2)@np.random.rand(2,5))
    print(A2.transpose()@A2)
    
    in_data = loadmat('/content/drive/My Drive/Colab Notebooks/movie.mat')
    M=in_data['M']
    M=np.column_stack(([1]*5, M))
    M = M.astype('float32')
    
    B = gram_schmidt(M)

    print(B)
    print(1/math.sqrt(5))

    # part b
    M=in_data['M']
    W=np.atleast_2d(B[:, 0])@M
    print(W)
    base=np.atleast_2d(B[:, 0]).transpose()@W
    print(base)
    print(M-base)
    '''
    A = np.array([[3,3,3,-1,-1,-1],[1,1,1,-3,-3,-3],[1,1,1,-3,-3,-3],[3,3,3,-1,-1,-1]], float)
    print(gram_schmidt(np.transpose(A)))


[[ 0.54772256 -0.18257419  0.          0.        ]
 [ 0.54772256 -0.18257419  0.          0.        ]
 [ 0.54772256 -0.18257419  0.          0.        ]
 [-0.18257419 -0.54772256  0.          0.        ]
 [-0.18257419 -0.54772256  0.          0.        ]
 [-0.18257419 -0.54772256  0.          0.        ]]


In [ ]:
    # part c
    M=in_data['M']
    T = B[:,[0, 1]]
    print(T)
    W_2=np.transpose(T)@M
    print(W_2)
    rank_two=T@W_2
    print(rank_two)
    print(M-rank_two)

[[ 4  7  2  8  7  4  2]
 [ 9  3  5  6 10  5  5]
 [ 4  8  3  7  6  4  1]
 [ 9  2  6  5  9  5  4]
 [ 4  9  2  8  7  4  1]]
[[ 0.44721359 -0.36514834]
 [ 0.44721359  0.54772258]
 [ 0.44721359 -0.36514834]
 [ 0.44721359  0.54772258]
 [ 0.44721359 -0.36514834]]
[[13.4164077  12.96919411  8.04984462 15.20526206 17.44133002  9.83869898
   5.81377667]
 [ 5.47722638 -6.02494717  3.46891001 -2.37346336  3.10376227  1.09544575
   3.46890986]]
[[3.99999976 7.99999929 2.3333332  7.66666603 6.66666619 3.9999997
  1.33333328]
 [9.00000041 2.50000027 5.50000025 5.50000037 9.50000048 5.00000027
  4.50000019]
 [3.99999976 7.99999929 2.3333332  7.66666603 6.66666619 3.9999997
  1.33333328]
 [9.00000041 2.50000027 5.50000025 5.50000037 9.50000048 5.00000027
  4.50000019]
 [3.99999976 7.99999929 2.3333332  7.66666603 6.66666619 3.9999997
  1.33333328]]
[[ 2.39303045e-07 -9.99999292e-01 -3.33333197e-01  3.33333966e-01
   3.33333814e-01  2.98609233e-07  6.66666724e-01]
 [-4.07825688e-07  4.99999734e-01 -5.00

In [ ]:
    # part d
    M=in_data['M']
    T = B[:,[0, 1, 2]]
    print(T)
    W_3=np.transpose(T)@M
    print(W_3)
    rank_three=T@W_3
    print(rank_three)
    print(M-rank_three)

[[ 4.47213590e-01 -3.65148336e-01 -6.32455111e-01]
 [ 4.47213590e-01  5.47722578e-01  3.16227555e-01]
 [ 4.47213590e-01 -3.65148336e-01  3.90354842e-07]
 [ 4.47213590e-01  5.47722578e-01 -3.16228002e-01]
 [ 4.47213590e-01 -3.65148336e-01  6.32455945e-01]]
[[ 1.34164077e+01  1.29691941e+01  8.04984462e+00  1.52052621e+01
   1.74413300e+01  9.83869898e+00  5.81377667e+00]
 [ 5.47722638e+00 -6.02494717e+00  3.46891001e+00 -2.37346336e+00
   3.10376227e+00  1.09544575e+00  3.46890986e+00]
 [ 8.75965952e-07  1.58114752e+00 -3.16227397e-01  3.16234728e-01
   3.16231715e-01  2.66410530e-06 -3.16228119e-01]]
[[3.99999921 6.99999446 2.53333283 7.46666176 6.46666382 3.99999802
  1.53333337]
 [9.00000068 3.00000268 5.40000043 5.6000025  9.60000167 5.00000111
  4.40000014]
 [3.99999976 7.99999991 2.33333307 7.66666616 6.66666631 3.9999997
  1.33333315]
 [9.00000013 1.99999715 5.6000002  5.39999809 9.39999916 4.99999942
  4.60000038]
 [4.00000031 9.00000544 2.1333333  7.86667057 6.86666881 4.000001

In [ ]:
    # part e
    M=in_data['M']
    M[:, [1, 0]] = M[:, [0, 1]]
    print(M)

    M=np.column_stack(([1]*5, M))
    M = M.astype('float32')

    B = gram_schmidt(M)

    M=in_data['M']
    print(M)
    
    T = B[:,[0, 1]]
    print(T)
    W_3=np.transpose(T)@M
    print(W_3)
    rank_three=T@W_3
    print(rank_three)
    print(M-rank_three)

[[ 7  4  2  8  7  4  2]
 [ 3  9  5  6 10  5  5]
 [ 8  4  3  7  6  4  1]
 [ 2  9  6  5  9  5  4]
 [ 9  4  2  8  7  4  1]]
[[ 7  4  2  8  7  4  2]
 [ 3  9  5  6 10  5  5]
 [ 8  4  3  7  6  4  1]
 [ 2  9  6  5  9  5  4]
 [ 9  4  2  8  7  4  1]]
[[ 0.44721359  0.19264843]
 [ 0.44721359 -0.44951293]
 [ 0.44721359  0.35318872]
 [ 0.44721359 -0.61005324]
 [ 0.44721359  0.5137291 ]]
[[12.96919411 13.4164077   8.04984462 15.20526206 17.44133002  9.83869898
   5.81377667]
 [ 6.22896536 -5.29783055 -3.43556288  2.37599745 -2.92183347 -1.05956587
  -3.43556294]]
[[7.00000023 4.97938114 2.93814413 7.25773201 7.23711319 4.1958762
  1.93814415]
 [2.9999994  8.38144318 5.14432985 5.73195826 9.11340173 4.87628845
  4.1443299 ]
 [8.00000018 4.12886585 2.38659785 7.63917534 6.76804118 4.02577318
  1.38659785]
 [1.99999936 9.23195856 5.69587618 5.35051489 9.58247379 5.04639149
  4.69587624]
 [9.0000006  3.27835016 1.8350513  8.02061886 6.29896895 3.85567008
  0.8350513 ]]
[[-2.30848674e-07 -9.79381141e-01